.. Elektroonilise hääletamise infosüsteem IVXV

.. Käsureautiliidi ivxv-consolidate-votes kasutusjuhend

.. SEE FAIL ON GENEREERITUD AUTOMAATTESTI POOLT:
.. * features/steps/autodoc.py
.. * features/autodoc-utilities.feature

.. _ivxv-consolidate-votes:

ivxv-consolidate-votes
``````````````````````

:command:`ivxv-consolidate-votes --help`:

.. code-block:: text

   Consolidate and export collected votes.

   This utility copies current ballot box from voting service to backup
   service and consolidates collected votes from all ballot box backup files.

   Usage: ivxv-consolidate-votes <output-file>
