.. Elektroonilise hääletamise infosüsteem IVXV

.. Käsureautiliidi ivxv-admin-helper kasutusjuhend

.. SEE FAIL ON GENEREERITUD AUTOMAATTESTI POOLT:
.. * features/steps/autodoc.py
.. * features/autodoc-utilities.feature

.. _ivxv-admin-helper:

ivxv-admin-helper
`````````````````

:command:`ivxv-admin-helper --help`:

.. code-block:: text

   Usage:
       ivxv-admin-helper check-service-config <service-type> <service-id>
           Check service configuration

       ivxv-admin-helper restart-service <service-type> <service-id>
                                         <systemctl-service-id>
           Restart service
