.. Elektroonilise hääletamise infosüsteem IVXV

.. Käsureautiliidi ivxv-agent-daemon kasutusjuhend

.. SEE FAIL ON GENEREERITUD AUTOMAATTESTI POOLT:
.. * features/steps/autodoc.py
.. * features/autodoc-utilities.feature

.. _ivxv-agent-daemon:

ivxv-agent-daemon
`````````````````

:command:`ivxv-agent-daemon --help`:

.. code-block:: text

   IVXV Collector Management Service agent daemon.

   Usage: ivxv-agent-daemon
