.. Elektroonilise hääletamise infosüsteem IVXV

.. Käsureautiliidi ivxv-eventlog-dump kasutusjuhend

.. SEE FAIL ON GENEREERITUD AUTOMAATTESTI POOLT:
.. * features/steps/autodoc.py
.. * features/autodoc-utilities.feature

.. _ivxv-eventlog-dump:

ivxv-eventlog-dump
``````````````````

:command:`ivxv-eventlog-dump --help`:

.. code-block:: text

   Dump IVXV Collector Management event log in human readable format.

   Usage: ivxv-eventlog-dump
