.. Elektroonilise hääletamise infosüsteem IVXV

.. Käsureautiliidi ivxv-logmonitor-copy-log kasutusjuhend

.. SEE FAIL ON GENEREERITUD AUTOMAATTESTI POOLT:
.. * features/steps/autodoc.py
.. * features/autodoc-utilities.feature

.. _ivxv-logmonitor-copy-log:

ivxv-logmonitor-copy-log
````````````````````````

:command:`ivxv-logmonitor-copy-log --help`:

.. code-block:: text

   Initialize IVXV Log Monitor.

   This utility exports collected IVXV log files from Log Collector
   Service to Log Monitor and initializes log analyzis in Log Monitor.

   Usage: ivxv-logmonitor-copy-log [--force]

   Options:
       --force     Don't ask user confirmation
