.. Elektroonilise hääletamise infosüsteem IVXV

.. Käsureautiliidi ivxv-db-reset kasutusjuhend

.. SEE FAIL ON GENEREERITUD AUTOMAATTESTI POOLT:
.. * features/steps/autodoc.py
.. * features/autodoc-utilities.feature

.. _ivxv-db-reset:

ivxv-db-reset
`````````````

:command:`ivxv-db-reset --help`:

.. code-block:: text

   Reset IVXV Collector Management Service database.

   Usage: ivxv-db-reset [--force]

   Options:
       --force     Don't ask user confirmation
