.. Elektroonilise hääletamise infosüsteem IVXV

.. Käsureautiliidi ivxv-cmd-remove kasutusjuhend

.. SEE FAIL ON GENEREERITUD AUTOMAATTESTI POOLT:
.. * features/steps/autodoc.py
.. * features/autodoc-utilities.feature

.. _ivxv-cmd-remove:

ivxv-cmd-remove
```````````````

:command:`ivxv-cmd-remove --help`:

.. code-block:: text

   Remove command from IVXV Collector Management Service.

   Usage: ivxv-cmd-remove <type>

   Options:

       <type>  Config type. Currently only voters list
               (value "voters") is supported.
