.. Elektroonilise hääletamise infosüsteem IVXV

.. Käsureautiliidi ivxv-votes-export kasutusjuhend

.. SEE FAIL ON GENEREERITUD AUTOMAATTESTI POOLT:
.. * features/steps/autodoc.py
.. * features/autodoc-utilities.feature

.. _ivxv-votes-export:

ivxv-votes-export
`````````````````

:command:`ivxv-votes-export --help`:

.. code-block:: text

   Export collected votes from IVXV voting service.

   Usage: ivxv-votes-export <output-file>
