.. Elektroonilise hääletamise infosüsteem IVXV

.. Käsureautiliidi ivxv-copy-log-to-logmon kasutusjuhend

.. SEE FAIL ON GENEREERITUD AUTOMAATTESTI POOLT:
.. * features/steps/autodoc.py
.. * features/autodoc-utilities.feature

.. _ivxv-copy-log-to-logmon:

ivxv-copy-log-to-logmon
```````````````````````

:command:`ivxv-copy-log-to-logmon --help`:

.. code-block:: text

   Copy IVXV log files from service hosts to Log Monitor.

   This utility transports collected IVXV log files from IVXV services
   (including Log Collector Service) to Log Monitor.

   Usage: ivxv-copy-log-to-logmon [<hostname> ...]

   Options:
       <hostname>  Service host name.
