.. Elektroonilise hääletamise infosüsteem IVXV

.. Käsureautiliidi ivxv-service kasutusjuhend

.. SEE FAIL ON GENEREERITUD AUTOMAATTESTI POOLT:
.. * features/steps/autodoc.py
.. * features/autodoc-utilities.feature

.. _ivxv-service:

ivxv-service
````````````

:command:`ivxv-service --help`:

.. code-block:: text

   Manage IVXV services.

   Usage: ivxv-service <action> <service-id> ...

   Options:
       <action>    Management action: start, stop, restart, ping
