.. Elektroonilise hääletamise infosüsteem IVXV

.. Käsureautiliidi ivxv-users-list kasutusjuhend

.. SEE FAIL ON GENEREERITUD AUTOMAATTESTI POOLT:
.. * features/steps/autodoc.py
.. * features/autodoc-utilities.feature

.. _ivxv-users-list:

ivxv-users-list
```````````````

:command:`ivxv-users-list --help`:

.. code-block:: text

   List IVXV Collector Management Service registered users.

   Usage: ivxv-users-list
