.. Elektroonilise hääletamise infosüsteem IVXV

.. Käsureautiliidi ivxv-collector-init kasutusjuhend

.. SEE FAIL ON GENEREERITUD AUTOMAATTESTI POOLT:
.. * features/steps/autodoc.py
.. * features/autodoc-utilities.feature

.. _ivxv-collector-init:

ivxv-collector-init
```````````````````

:command:`ivxv-collector-init --help`:

.. code-block:: text

   Initialize IVXV Collector.

   Usage: ivxv-collector-init [--force]

   Options:
       --force     Don't ask user confirmation
