// Package nizkp implements ElGamal non-interactive zero-knowledge proof.
// ElGamal non-interactive zero-knowledge proof is a collection of commitments
// that prover provides to verifier in order to check data integrity and completeness.
// Commitment is a unit of something that is being either proved (prover) or verified (verifier).
package nizkp

import (
	"fmt"
	asn_1 "tivi.io/core/encoding/asn1"

	"golang.org/x/crypto/cryptobyte"
	"golang.org/x/crypto/cryptobyte/asn1"
	"golang.org/x/crypto/sha3"

	"tivi.io/core/math/group"
)

// Commitment is a unit of something that is being either proved (prover) or verified (verifier).
type Commitment interface {
	// Count returns an amount of commitments to be either created (prover) or verified (verifier).
	// Verifier should generate exactly the same amount of commitments as prover does.
	Count() uint64

	// Create is used by a prover to create a set of commitments to verifier.
	// Random scalar s is used in a creation of a commitments set.
	Create(s *group.Scalar) (commitments []group.Element, err error)

	// Verify is used by a verifier to parse ElGamal non-interactive zero-knowledge proof into
	// a set of commitments, that were generated by a prover. After parsing, commitments
	// are also verified and returned.
	Verify(nizkp *Proof) (commitments []group.Element, err error)
}

// Challenge creates ElGamal non-interactive zero-knowledge proof challenge by summing up all
// commitments into a resulting one, and then hashing it as SHAKE256(ID || sum).
// If salt non-nil then hashing is SHAKE256(ID || sum || salt). Salt is used to add a
// uniqueness to a set of commitments.
func Challenge(g group.Group, commitments []group.Element, salt []byte) (challenge *group.Scalar, err error) {
	sum := g.Identity()

	// Sum up all commitments, this will ensure that even if order of elements in a commitments
	// slice changes, we still get the same challenge
	for _, commitment := range commitments {
		sum, err = sum.Op(commitment)
		if err != nil {
			return nil, fmt.Errorf("failed to sum up ElGamal non-interactive zero-knowledge proof commitments: %v", err)
		}
	}

	// ASN.1 marshal sum
	sumDer, err := sum.Marshal()
	if err != nil {
		return nil, fmt.Errorf("failed to ASN.1 marshal summed ElGamal non-interactive zero-knowledge proof commitment: %v", err)
	}

	// If salt is nil, then
	// digest = SHAKE256([]byte("NIZKP") || sumDer)
	//
	// otherwise,
	// digest = SHAKE256([]byte("NIZKP") || sumDer || salt)
	var builder cryptobyte.Builder
	builder.AddASN1(asn1.SEQUENCE, func(builder *cryptobyte.Builder) {
		builder.AddASN1(asn1.PrintableString, func(builder *cryptobyte.Builder) {
			builder.AddBytes([]byte("NIZKP"))
		})
		builder.AddBytes(sumDer)
		builder.AddASN1OctetString(salt)
	})

	der, err := builder.Bytes()
	if err != nil {
		return nil, fmt.Errorf("failed to ASN.1 marshal ElGamal non-interactive zero-knowledge proof challenge: %v", err)
	}

	// Variable length hash
	digest := sha3.NewShake256()

	// Shake instance does not fail
	digest.Write(der) //nolint: errcheck

	// Create group scalar from hash bytes
	challenge, err = group.ScalarValueOfReader(digest, g.Order())
	if err != nil {
		return nil, fmt.Errorf("failed to create group scalar from ASN.1 marshalled ElGamal non-interactive zero-knowledge proof challenge: %v", err)
	}
	return
}

// Verify parses non-interactive zero-knowledge proof (challenge, response) for a specific
// commitment, verifies and returns it. Specific commitment is extracted by providing correct
// base and element.
func Verify(base, element group.Element, challenge, response *group.Scalar) (commitment group.Element, err error) {
	c1, err := element.Scale(challenge)
	if err != nil {
		return nil, fmt.Errorf("failed to scale element by ElGamal non-interactive zero-knowledge proof challenge: %v", err)
	}

	c2, err := base.Scale(response)
	if err != nil {
		return nil, fmt.Errorf("failed to scale base by ElGamal non-interactive zero-knowledge proof response: %v", err)
	}

	c3 := c1.Inverse()

	commitment, err = c2.Op(c3)
	if err != nil {
		return nil, fmt.Errorf("failed to compute a ElGamal non-interactive zero-knowledge proof commitment: %v", err)
	}

	lhs, err := base.Scale(response)
	if err != nil {
		return nil, fmt.Errorf("failed to calculate ElGamal non-interactive zero-knowledge proof lhs expression: %v", err)
	}

	rhs, err := c1.Op(commitment)
	if err != nil {
		return nil, fmt.Errorf("failed to calculate ElGamal non-interactive zero-knowledge proof rhs expression: %v", err)
	}

	if err = lhs.Equal(rhs); err != nil {
		return nil, fmt.Errorf("ElGamal non-interactive zero-knowledge proof lhs not equal to rhs: %v", err)
	}
	return
}

// Proof is ElGamal non-interactive zero-knowledge proof.
type Proof struct {
	// challenge is the hash that both prover and verifier create on their sides
	// and then compare them to be equal.
	challenge *group.Scalar

	// response is the prover response, that verifier verifies.
	response *group.Scalar
}

// NewProof returns new ElGamal non-interactive zero-knowledge proof.
func NewProof(challenge, response *group.Scalar) *Proof {
	return &Proof{
		challenge: challenge,
		response:  response,
	}
}

// Challenge returns ElGamal non-interactive zero-knowledge proof challenge.
func (p *Proof) Challenge() *group.Scalar {
	return p.challenge
}

// Response returns ElGamal non-interactive zero-knowledge proof response.
func (p *Proof) Response() *group.Scalar {
	return p.response
}

// ASN1Marshal ASN.1 marshals ElGamal non-interactive zero-knowledge proof as
//
//	p ::= SEQUENCE {
//		challenge	INTEGER
//		response	INTEGER
//	}
func (p *Proof) MarshalASN1() (der []byte, err error) {
	challengeDer, err := p.challenge.Marshal()
	if err != nil {
		return nil, fmt.Errorf("failed to ASN.1 marshal ElGamal non-interactive zero-knowledge proof challenge: %v", err)
	}

	responseDer, err := p.response.Marshal()
	if err != nil {
		return nil, fmt.Errorf("failed to ASN.1 marshal ElGamal non-interactive zero-knowledge proof response: %v", err)
	}

	var builder cryptobyte.Builder
	builder.AddASN1(asn1.SEQUENCE, func(builder *cryptobyte.Builder) {
		builder.AddBytes(challengeDer)
		builder.AddBytes(responseDer)
	})

	der, err = builder.Bytes()
	if err != nil {
		return nil, fmt.Errorf("failed to ASN.1 marshal ElGamal non-interactive zero-knowledge proof: %v", err)
	}
	return
}

// ASN1UnmarshalProof ASN.1 unmarshalls ElGamal non-interactive zero-knowledge proof.
func ASN1UnmarshalProof(g group.Group, data []byte) (*Proof, error) {
	der := cryptobyte.String(data)
	var sequence, challengeDer, responseDer cryptobyte.String

	if !der.ReadASN1(&sequence, asn1.SEQUENCE) {
		return nil, fmt.Errorf("failed to ASN.1 unmarshal ElGamal non-interactive zero-knowledge proof SEQUENCE")
	}

	if !sequence.ReadAnyASN1Element(&challengeDer, nil) {
		return nil, fmt.Errorf("failed to ASN.1 unmarshal ElGamal non-interactive zero-knowledge proof challenge")
	}

	if !sequence.ReadAnyASN1Element(&responseDer, nil) {
		return nil, fmt.Errorf("failed to ASN.1 unmarshal ElGamal non-interactive zero-knowledge proof response")
	}

	if !der.Empty() || !sequence.Empty() {
		return nil, fmt.Errorf("trailing bytes left while ASN.1 unmarshalling ElGamal non-interactive zero-knowledge proof")
	}

	challenge, err := group.UnmarshalScalar(asn_1.DER(challengeDer), g.Order())
	if err != nil {
		return nil, fmt.Errorf("failed to create group scalar from ElGamal non-interactive zero-knowledge proof challenge: %v", err)
	}

	response, err := group.UnmarshalScalar(asn_1.DER(responseDer), g.Order())
	if err != nil {
		return nil, fmt.Errorf("failed to create group scalar from ElGamal non-interactive zero-knowledge proof response: %v", err)
	}

	return NewProof(challenge, response), nil
}
