package main

const (
	_WEBEID_CHALLENGEREQ       = "RPC.ChallengeReq"
	_WEBEID_EXPIRED            = "Current time >= 'electionstoptime' from election configuration file"
	_WEBEID_SESSION_ID         = "Malformed SessionID"
	_WEBEID_SESSION_ID_EXPIRED = "SessionID has been expired"
	_WEBEID_CHALLENGE          = "Failed to generate 44 byte random challenge"
	_WEBEID_PAYLOAD            = "Failed to extract payload from a Bearer token"
	_WEBEID_BEARER             = "Failed to create new Bearer token"
	_WEBEID_CHALLENGERESP      = "RPC.ChallengeResp"
	_WEBEID_TOKENREQ           = "RPC.TokenReq"
	_WEBEID_SIG                = "Failed to extract signature from a Bearer token"
	_WEBEID_SIG_VERIFY         = "Unable to verify Bearer token signature"
	_WEBEID_SIG_DATA           = "Signature is verified, but extracted data from signature is empty"
	_WEBEID_TOKEN              = "Failed to create new Web-eID token"
	_WEBEID_CERT               = "Failed to verify voter certificate, that was parsed from certificate"
	_WEBEID_TOKEN_VERIFY       = "Failed to verify Web-eID token"
	_WEBEID_AUTHTOKEN          = "Failed to create server.AuthToken (authentication token)"
	_WEBEID_TOKENRESP          = "RPC.TokenResp"
	_WEBEID_BAD_URL            = "Incorrect Web-eID URI"
	_WEBEID_START              = "Failed to transform service start time from election configuration file to RFC3339 format"
	_WEBEID_AUTH_STOP          = "Failed to transform authentication stop time from election configuration file to RFC3339 format"
	_WEBEID_STOP               = "Failed to transform service stop time from election configuration file to RFC3339 format"
	_WEBEID_TICKET             = "Failed to create a Web-eID ticket (AES cipher) that is used for cookie signing"
	_WEBEID_TICKET_AUTH        = "Web-eID service should be configured for ticket based authentication"
	_WEBEID_AUTH               = "Failed to parse authentication configuration for webeid service"
	_WEBEID_TLS_AUTH           = "Web-eID service should be also configured for voter certificate authentication"
	_WEBEID_TLS_AUTH_CFG       = "Failed to parse TLS configuration for voter certificate authentication"
	_WEBEID_SERVER             = "Failed to parse server configuration for webeid service"
	_WEBEID_BEARER_COOKIE      = "Failed to create AES shared secret to encrypt Bearer tokens"
	_WEBEID_SERVER_SERVE       = "Failed to serve webeid service to clients"
)
