package cryptoutil

const (
	_CUTIL_PEM               = "Failed to PEM decode"
	_CUTIL_PEM_H             = "Unexpected PEM header"
	_CUTIL_PEM_H_BAD         = "Invalid PEM header"
	_CUTIL_CERT_PEM          = "Failed to parse PEM certificate"
	_CUTIL_CERT_B64          = "base-64 decoding of a certificate content failed"
	_CUTIL_CERT_PARSE        = "Failed to parse certificate content"
	_CUTIL_ECDSA2XML         = "Failed to convert ECDSA signature to XML format"
	_CUTIL_ASN1ECDSA         = "ASN.1 marshalling of ECDSA signature failed"
	_CUTIL_UASN1ECDSA        = "ASN.1 unmarshalling of ECDSA signature failed"
	_CUTIL_ECDSA_SIZE        = "ECDSA signature has invalid size"
	_CUTIL_44B_RAND          = "Cannot generate 44-byte random value"
	_CUTIL_ATTR_ASN1         = "Attribute value ASN.1 marshalling failed"
	_CUTIL_RDN_PREFIX        = "Missing ',' prefix in relative distinguish name string"
	_CUTIL_RDN_NO            = "Missing relative distinguish name string"
	_CUTIL_RDN_ATTR_NO       = "Missing relative distinguish name attribute"
	_CUTIL_RDN_EQ            = "Missing '=' in relative distinguish name string"
	_CUTIL_ATTR_UNKNOWN      = "Unknown relative distinguish name attribute"
	_CUTIL_ATTR_SHORT        = "Relative distinguish name attribute's Object Identifier is too short"
	_CUTIL_ATTR_HEX          = "Missing relative distinguish name attribute base-16 value"
	_CUTIL_ATTR_HEX_DEC      = "Failed to base-16 decode relative distinguish name attribute value"
	_CUTIL_ATTR_UASN1        = "Failed to ASN.1 unmarshal relative distinguish name attribute value"
	_CUTIL_ATTR_UTF8         = "Relative distinguish name attribute value is invalid UTF-8"
	_CUTIL_ATTR_SLASH        = "Relative distinguish name attribute value has unescaped trailing slash"
	_CUTIL_ATTR_1_CHAR       = "Relative distinguish name attribute value's first char is incorrectly escaped"
	_CUTIL_ATTR_HEX_PAIR     = "Invalid relative distinguish name attribute value base-16 pair"
	_CUTIL_ATTR_UNKNOWN_CHAR = "Relative distinguish name attribute value contains unsupported escape chars"
	_CUTIL_ATTR_CHAR_EMPTY   = "Relative distinguish name attribute value has ' ' in leading or trailing character, which is not allowed"
	_CUTIL_ATTR_SPACE        = "Relative distinguish name attribute value has unescaped trailing space"
)
