package main

const (
	_SMARTID_EXPIRED_AUTH_SESSION = "Request timeout expired for this voter between RPC.Authenticate and RPC.AuthenticateStatus"
	_SMARTID_CHALREQ              = "RPC.ChallengeReq"
	_SMARTID_CHAL_COOKIE_MARSHAL  = "Failed to ASN.1 DER marshal a cookie data"
	_SMARTID_CHAL_COOKIE          = "Failed to encrypt a cookie"
	_SMARTID_CHALRESP             = "RPC.ChallengeResp"
	_SMARTID_AUTHREQ              = "RPC.AuthenticateReq"
	_SMARTID_EXPIRED              = "Current time >= 'electionstoptime' from election configuration file"
	_SMARTID_SESSION_ID           = "Malformed SessionID"
	_SMARTID_SESSION_ID_EXPIRED   = "SessionID has been expired"
	_SMARTID_CHAL                 = "Failed to create a challenge"
	_SMARTID_COOKIE_EXTRACT       = "Failed to decrypt a cookie"
	_SMARTID_COOKIE_UNMARSHAL     = "Failed to ASN.1 DER unmarshal a cookie data"
	_SMARTID_COOKIE_SESSIONID     = "Tampered cookie SessionID"
	_SMARTID_AUTH_RESP            = "Smart-ID provider responded with error"
	_SMARTID_NO_RESP              = "Cannot reach Smart-ID provider"
	_SMARTID_DATA_TOKEN_CREATE    = "Failed to create data token cookie (AES cipher)"
	_SMARTID_SAME_AUTH_SESSION    = "Smart-ID provider has been issued duplicate authentication session code"
	_SMARTID_AUTHRESP             = "RPC.AuthenticateResp"
	_SMARTID_AUTHSTATUSREQ        = "RPC.AuthenticateStatusReq"
	_SMARTID_UNKNOWN_AUTH_SESSION = "Voter send non-existing Smart-ID authentication session code"
	_SMARTID_SIG_RESP             = "Smart-ID provider returned back voter's signature"
	_SMARTID_NO_CERT_RESP         = "Smart-ID provider didn't return back voter's certificate"
	_SMARTID_CERT_RESP            = "Smart-ID provider returned back voter's certificate"
	_SMARTID_VERIFY_SIG           = "Failed to verify voter's signature"
	_SMARTID_VOTER_ID             = "Cannot extract voter's personal code from certificate's 'Subject' field"
	_SMARTID_AUTH_TOKEN_CREATE    = "Failed to create IVXV authentication token cookie (AES cipher)"
	_SMARTID_AUTHSTATUSRESP       = "RPC.AuthenticateStatusResp"
	_SMARTID_GETCERTREQ           = "RPC.GetCertificateReq"
	_SMARTID_VOTER_NO_AUTH        = "Voter has not been authenticated"
	_SMARTID_VOTER_NO_PHONENR     = "Authenticated voter should have a phone nr. parsed from IVXV authentication token cookie"
	_SMARTID_CERT                 = "Smart-ID signing certificate of a voter"
	_SMARTID_GETCERTRESP          = "RPC.GetCertificateResp"
	_SMARTID_GETCERTSTATUSREQ     = "RPC.GetCertificateStatusReq"
	_SMARTID_GETCERTSTATUSRESP    = "RPC.GetCertificateStatusReq"
	_SMARTID_SIGNREQ              = "RPC.SignReq"
	_SMARTID_SIGNRESP             = "RPC.SignResp"
	_SMARTID_SIGNSTATUSREQ        = "RPC.SignStatusReq"
	_SMARTID_SIGNSTATUSRESP       = "RPC.SignStatusResp"
	_SMARTID_START                = "Failed to transform service start time from election configuration file to RFC3339 format"
	_SMARTID_AUTH_STOP            = "Failed to transform authentication stop time from election configuration file to RFC3339 format"
	_SMARTID_STOP                 = "Failed to transform service stop time from election configuration file to RFC3339 format"
	_SMARTID_CLIENT_CONF          = "Failed to configure Smart-ID API client"
	_SMARTID_TICKET_AUTH          = "Smart-ID service should be configured for ticket based authentication"
	_SMARTID_TICKET               = "Failed to create a Smart-ID ticket (AES cipher) that is used for cookie signing"
	_SMARTID_AUTH                 = "Failed to parse authentication configuration for smartid service"
	_SMARTID_SERVER               = "Failed to parse server configuration for smartid service"
	_SMARTID_SERVER_SERVE         = "Failed to serve smartid service to clients"
)
