package yaml

const (
	_YAML_INT64           = "Failed parsing value to base-10 integer"
	_YAML_BOOL            = "bool type can only be 'true' or 'false'"
	_YAML_B64             = "Failed parsing value to base-64 []byte"
	_YAML_SCALAR          = "Failed to parse value to YAML scalar"
	_YAML_SCALAR_ERR      = "YAML scalar reports an error"
	_YAML_ARRAY           = "Invalid array length"
	_YAML_SLICE           = "Failed to parse value to slice"
	_YAML_SEQUENCE_ERR    = "YAML sequence reports an error"
	_YAML_STRING          = "Failed to parse value to string"
	_YAML_MAPPING         = "Failed to parse value to YAML mapping"
	_YAML_MAPPING_ERR     = "YAML mapping reports an error"
	_YAML_CTX_DONE        = "Context is cancelled"
	_YAML_MORE_BYTES_LEFT = "Expected no bytes or EOF bytes, but got something different"
	_YAML_EOF             = "Expected EOF bytes, but got something different"
	_YAML_READ_RUNE       = "This bufio.Reader hasn't called Reader.ReadRune method just before calling Reader.UnreadRune method"
	_YAML_ERR_WRAP        = "Wrapper for YAML lexer errors"
	_YAML_TRAILING        = "Trailing (extra) data left after parsing YAML node"
	_YAML_NO_KEY_MAPPING  = "YAML mapping has no key, i.e. ':value'"
	_YAML_SEQ_EXPECT      = "Expected YAML sequence, but got something different"
	_YAML_SCALAR_EMPTY    = "YAML scalar is empty string"
	_YAML_BDOC_TO_YAML    = "Cannot structure .bdoc container content into YAML format"
	_YAML_BDOC_YAML_PARSE = "Failed to parse YAML representation of a .bdoc container content"
	_YAML_KEY_UNIQ        = "YAML key must be unique"
	_YAML_MAPPING_DEPTH   = "Invalid YAML mapping depth (expected doesn't match actual)"
	_YAML_KEY_MAPPING     = "YAML mapping has a format of 'key:value'"
	_YAML_MAPPING_EOF     = "YAML mapping should be the only content in a file row, so EOF is expected at the end of YAML mapping"
	_YAML_KEY_LINE        = "Unexpected YAML mapping key"
	_YAML_SYN_WRAP        = "Wrapper for YAML syntactical processing errors"
	_YAML_NOT_PTR_OR_NIL  = "Value is either nil or not a pointer"
)
