package ocsp

const (
	_OCSP_RESPONDER        = "Failed to parse OCSP response intermediate certificates from an election configuration"
	_OCSP_URI              = "No OCSP provider URI"
	_OCSP_REQ              = "Failed to create OCSP client request"
	_OCSP_CONN             = "Could not contact OCSP provider, trying again"
	_OCSP_FAIL             = "OCSP provider responded with error"
	_OCSP_RESP             = "Failed to verify OCSP provider response"
	_OCSP_PARSE            = "Could not parse OCSP response"
	_OCSP_RAW2BS           = "Failed to parse OCSP response to basic OCSP response (formatting)"
	_OCSP_ASN1             = "ASN.1 marshalling OCSP client request failed"
	_OCSP_REQ_PREP         = "Failed to prepare OCSP client request"
	_OCSP_REQ_HTTP         = "Failed to create HTTP request to be sent to OCSP provider"
	_OCSP_REQ_INFO         = "Info about HTTP request to OCSP provider"
	_OCSP_REQ_SEND         = "Sending OCSP request to OCSP provider over HTTP"
	_OCSP_REQ_FAIL         = "OCSP provider responded with error"
	_OCSP_REQ_CLOSE        = "Failed to close HTTP connection between OCSP client and provider"
	_OCSP_REQ_RESP         = "Successfully received OCSP response from OCSP provider"
	_OCSP_RESP_DUMP        = "Failed to parse HTTP OCSP response"
	_OCSP_RESP_OK          = "Successfully parsed OCSP response"
	_OCSP_RESP_STAT        = "OCSP response has non-OK status"
	_OCSP_RESP_HTTP_HEADER = "OCSP response 'Content-Type' HTTP header is not a 'application/ocsp-response'"
	_OCSP_RESP_READ        = "Failed to read OCSP response"
	_OCSP_RESP_READ_OK     = "Successfully read OCSP response"
	_OCSP_RESP_BASIC       = "Failed to parse OCSP response as basic OCSP response"
	_OCSP_AUTHKID          = "Missing 'AuthorityKeyId' field in a x509 certificate"
	_OCSP_RESP_ASN1        = "ASN.1 unmarshalling OCSP response failed"
	_OCSP_RESP_TYPE        = "OCSP response type is not basic"
	_OCSP_RESP_B_ASN1      = "ASN.1 unmarshalling basic OCSP response failed"
	_OCSP_COMMON_CHECKS    = "Failed to perform common OCSP checks"
	_OCSP_OFF              = "OCSP thisUpdate value > now + (OCSP allowed offset)"
	_OCSP_EXPIRED          = "OCSP is response is expired"
	_OCSP_BETWEEN          = "OCSP response producedAt is not between thisUpdate and (now + OCSP allowed offset) timestamps"
	_OCSP_STORED           = "Check stored in .bdoc container OCSP response failed"
	_OCSP_PAT              = "OCSP producedAt >= thisUpdate"
	_OCSP_SUB              = "(producedAt - thisUpdate) > OCSP allowed offset"
	_OCSP_UNIQ             = "Only 1 OCSP response is allowed"
	_OCSP_CERT             = "User certificate from OCSP response doesn't match provided user certificate"
	_OCSP_NONCE            = "Nonce calculated not equal to nonce from OCSP response"
	_OCSP_RESPONDER_GET    = "Fetching all responder certificates from an election configuration failed"
	_OCSP_ALG_UNKNOWN      = "Unsupported signature algorithm from OCSP response"
	_OCSP_SIG_VERIFY       = "Checking signature from OCSP response failed"
	_OCSP_CERT_PARSE       = "Parsing OCSP responder certificate from an OCSP response failed"
	_OCSP_CERT_VERIFY      = "Verify OCSP responder certificate against OCSP intermediate CA certificates"
	_OCSP_N_ISSUER         = "No OCSP CA certificate provided to verify OCSP responder certificate"
)
