.. Elektroonilise hääletamise infosüsteem IVXV

.. Käsureautiliidi ivxv-create-data-dirs kasutusjuhend

.. SEE FAIL ON GENEREERITUD AUTOMAATTESTI POOLT:
.. * features/steps/autodoc.py
.. * features/autodoc-utilities.feature

.. _ivxv-create-data-dirs:

ivxv-create-data-dirs
`````````````````````

:command:`ivxv-create-data-dirs --help`:

.. code-block:: text

   Create IVXV Collector Management Service data directories.

   NOTE: Directory owners and permissions are not set by this utility!

   Usage: ivxv-create-data-dirs
