.. Elektroonilise hääletamise infosüsteem IVXV

.. Käsureautiliidi ivxv-backup kasutusjuhend

.. SEE FAIL ON GENEREERITUD AUTOMAATTESTI POOLT:
.. * features/steps/autodoc.py
.. * features/autodoc-utilities.feature

.. _ivxv-backup:

ivxv-backup
```````````

:command:`ivxv-backup --help`:

.. code-block:: text

   Backup IVXV collector data.

   Usage: ivxv-backup management-conf
          ivxv-backup ballot-box [<voting_service_id>]
          ivxv-backup log
