.. Elektroonilise hääletamise infosüsteem IVXV

.. Käsureautiliidi ivxv-voter-list-download kasutusjuhend

.. SEE FAIL ON GENEREERITUD AUTOMAATTESTI POOLT:
.. * features/steps/autodoc.py
.. * features/autodoc-utilities.feature

.. _ivxv-voter-list-download:

ivxv-voter-list-download
````````````````````````

:command:`ivxv-voter-list-download --help`:

.. code-block:: text

   Download next available voter list changeset from VIS to IVXV Collector
   Management Service.

   Usage:
       ivxv-voter-list-download [--output-report=<filepath>] [--log-level=<level>]

   Options:
       --output-report=<filepath>  Write JSON report about HTTP request to VIS.
       --log-level=<level>         Logging level [Default: INFO].
