package smartid

const (
	_SID_RAND          = "Generate random value for Smart-ID challenge"
	_SID_SESS          = "Cannot create Smart-ID session via Smart-ID provider"
	_SID_SESS_STAT     = "HTTP get session status from Smart-ID provider failed"
	_SID_CERT          = "Parsing client Smart-ID certificate failed"
	_SID_EXTKEY_SK     = "Not an SK x509 extended key usage"
	_SID_EXTKEY        = "Unknown x509 extended key usage"
	_SID_CERT_VERIFY   = "Failed to verify client Smart-ID certificate"
	_SID_OCSP          = "Failed to check client Smart-ID certificate against OCSP provider"
	_SID_OCSP_N_GOOD   = "OCSP status of client Smart-ID certificate is not good"
	_SID_ALG           = "Unsupported Smart-ID signature algorithm"
	_SID_SIG           = "Failed to verify signature of a Smart-ID client"
	_SID_N_ID          = "No voter ID"
	_SID_HTTP_CERT     = "Failed to get Smart-ID certificate from Smart-ID provider"
	_SID_URI           = "Failed to prepare request URI for Smart-ID provider"
	_SID_JSON          = "JSON marshalling request for Smart-ID provider failed"
	_SID_HTTP          = "Failed to prepare HTTP request URI for Smart-ID provider"
	_SID_HTTP_READY    = "HTTP request for Smart-ID provider has been prepared successfully"
	_SID_HTTP_SEND     = "Sending HTTP request to Smart-ID provider"
	_SID_RESP_ERR      = "Smart-ID provider responded with error"
	_SID_CLOSE         = "Cannot gracefully close HTTP connection with Smart-ID provider"
	_SID_RESP          = "Successfully received Smart-ID provider response"
	_SID_RESP_PARSE    = "Cannot parse HTTP Smart-ID provider response"
	_SID_RESP_PARSE_OK = "Successfully parsed HTTP Smart-ID provider response"
	_SID_RESP_READ     = "Failed to read Smart-ID response"
	_SID_RESP_READ_OK  = "Successfully read Smart-ID response"
	_SID_RESP_JSONCODE = "JSON unmarshalling error code from Smart-ID provider failed"
	_SID_ERRCODE       = "Error status code from Smart-ID provider"
	_SID_RESP_JSON     = "JSON unmarshalling response for Smart-ID provider failed"
	_SID_N_HASH        = "No hashing algorithm provided"
	_SID_N_HASH_T      = "No hashing type provided"
	_SID_SESS_STATE    = "Unknown Smart-ID session state"
	_SID_SESS_RES      = "Unknown Smart-ID session result"
	_SID_IN            = "Wraps errors which are caused by bad input to smartid functions"
	_SID_VERIF_CODE    = "Error returned if the voter 3 different code was displayed in app and selected wrong code"
	_SID_ACC           = "Error returned that are caused by user account configuration"
	_SID_CANCEL        = "Error returned if the voter canceled the operation"
	_SID_EXP           = "Error returned if the session expired before the voter did any action"
	_SID_CERT_ERR      = "Wraps errors which are caused by errors with the voter's certificate (revoked, suspended, not activated, etc)"
	_SID_STAT_ERR      = "Wraps errors which are caused by an unexpected session status: this is a catch-all for other types of Smart-ID problems"
	_SID_CA            = "No CA certificates provided to verify Smart-ID provider certificate"
	_SID_CA_PARSE      = "Failed to parse Smart-ID CA certificate"
	_SID_ICA_PARSE     = "Failed to parse Smart-ID intermediate CA certificate"
	_SID_OCSP_CFG      = "Failed to configure Smart-ID OCSP client"
	_SID_HASH          = "Unsupported hash algorithm"
)
