#!/bin/sh -eu

# gentmpl.sh: Generate a Go source file with a template file inlined. This way
# we can use template-specific syntax-highlighting when editing the template,
# yet still embed it into the final binary.

tmpl="gen.tmpl"
go="gentmpl.go" # NB! if "gen.tmpl.go", then go clean will delete gen.tmpl.
var="$1"

# Use a variable for the header of the vim modeline used in the generated file
# so that vim will not pick it up and apply to this file.
vimhdr="vim"

cat > "$go" <<HERE
// Generated by gentmpl.sh. DO NOT EDIT!

package main

import "text/template"

var $var = template.Must(template.New("$var").Funcs(funcMap).Parse(header + \`
HERE

cat "$tmpl" >> "$go"
cat >> "$go" <<HERE
\`))

// Override the modeline in the template.
// $vimhdr: set ft=go:
HERE
