# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
import os
import sys
sys.path.insert(0, os.path.abspath('.'))

import documents

# -- Project information -----------------------------------------------------

project = documents.project
copyright = documents.copyright
author = documents.author
release = documents.release

document = os.environ['IVXV_DOCUMENT']

version = documents.get(document, 'version')
today = documents.get(document, 'changed')
document_prefix = documents.get(document, 'document_prefix')
document_type = documents.get(document, 'document_type')
document_title = documents.get(document, 'document_title')
document_target_name = documents.get(document, 'document_target_name')

language = documents.get(document, 'lang')

document_number = f'{document_prefix}-{version}'

today_fmt = "%d.%m.%Y"

numfig = True
numfig_format = {
    'section': '{name} (ptk. {number})'
}

# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.autosummary',
    'sphinx.ext.imgmath',
    'sphinx.ext.todo',
    'sphinx_rtd_theme',
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']
source_suffix = '.rst'

# The master toctree document.
master_doc = 'index'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = False

# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'sphinx_rtd_theme'

# Add any paths that contain custom themes here, relative to this directory.
# html_theme_path = []

# The name for this set of Sphinx documents.
# "<project> v<release> documentation" by default.
#
html_title = f'{document_title} v{release}'

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

# List of CSS files.
html_css_files = ['custom.css']

# HTML logo image.
html_logo = '_static/ivxv.png'

# -- Options for LaTeX output ------------------------------------------------

latex_preamble_lines = [
    '\\makeatletter',
    '\\IVXVDefineDocumentVersion{%s}' % version,
    '\\IVXVDefineDocumentNumber{%s}' % document_number,
    '\\IVXVDefineDocumentType{%s}' % document_type,
    '\\IVXVDefineDocumentSecurity{}',
    '\\pagestyle{IVXVFancy}',
    '\\makeatother',
    '\\newcommand{\\tablecontinued}{\\sphinxtablecontinued}',
]

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    'papersize': 'a4paper',
    'preamble': ''.join(latex_preamble_lines),

    # The font size ('10pt', '11pt' or '12pt').
    'pointsize': '12pt',

    # Additional stuff for the LaTeX preamble.
    # 'preamble': '',

    # Latex figure (float) alignment
    # 'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (master_doc,
     f'{document_target_name}.tex',
     document_title,
     author,
     'ivxv-technical'),
]

latex_additional_files = [
    'ivxv-technical/ivxv-common.cls',
    'ivxv-technical/ivxv-technical.cls'
]

# The name of an image file (relative to this directory) to place at the top of
# the title page.
#
latex_logo = html_logo

# If true, show page references after internal links.
#
latex_show_pagerefs = False

# If true, show URL addresses after external links.
#

latex_show_urls = 'footnote'


# -- Options for Texinfo output ----------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (master_doc,
     document_target_name,
     document_title,
     author,
     document_target_name,
     'One line description of project.',
     'Miscellaneous'),
]
