package main

const (
	_STORAGE_WAL_OPEN            = "Failed to open wal/ directory"
	_STORAGE_ETCD_OPEN           = "Failed to list all files/directories in etcd root directory"
	_STORAGE_ETCD_MEM            = "Prepare to fetch all etcd nodes from etcd cluster"
	_STORAGE_ETCD_MEM_FAIL       = "Failed to list all etcd nodes"
	_STORAGE_ETCD_MEM_LIST       = "List all etcd nodes"
	_STORAGE_SAME_ID_CLIENT      = "Each etcd client should have a single URI"
	_STORAGE_SAME_ID             = "Each etcd node should have a single URI"
	_STORAGE_PING_CLIENT         = "Starting to ping an etcd client"
	_STORAGE_PING_CLIENT_CFG     = "Failed to create etcd client"
	_STORAGE_PING_CLIENT_PRUNED  = "Removed etcd node is still alive"
	_STORAGE_PING_CLIENT_FAIL    = "Failed to ping an etcd client"
	_STORAGE_PRUNE_NODE          = "Starting to prune an etcd node"
	_STORAGE_PRUNE_NODE_FAIL     = "Failed to prune an etcd node"
	_STORAGE_PRUNE_NODE_OK       = "Successfully pruned an etcd node"
	_STORAGE_NODE_URI_USED       = "etcd node URI is already in-use"
	_STORAGE_ADD_NODE            = "Starting to add an etcd node"
	_STORAGE_ADD_NODE_FAIL       = "Failed to add an etcd node"
	_STORAGE_ADD_NODE_OK         = "Successfully added an etcd node"
	_STORAGE_UPDATE_CLUSTER      = "Update cluster membership"
	_STORAGE_ETCD_CONN_CLOSE     = "Failed to close etcd connection"
	_STORAGE_ETCD_CLUSTER_UPDATE = "Failed to update etcd cluster membership"
	_STORAGE_ETCD_CLUSTER_PRUNE  = "Failed to prune etcd cluster inactive nodes"
	_STORAGE_ETCD_CLUSTER_ADD    = "Failed to add etcd nodes into a cluster"
	_STORAGE_ETCD_CLUSTER_OK     = "etcd cluster is successfully updateed and ready to use"
	_STORAGE_ETCD_SYSLOG         = "Failed to create syslog instance for etcd output"
	_STORAGE_ETCD_SYSLOG_CLOSE   = "Failed to close etcd syslog instance"
	_STORAGE_ETCD_ESCAPE         = "Some of etcd native logs are not JSON format"
	_STORAGE_ETCD_FORMAT         = "etcd native log is JSON format, but doesn't match an expected pattern on IVXV side"
	_STORAGE_ETCD_UNKNOWN_LVL    = "Unknown log level detected in etcd native log"
	_STORAGE_CFG                 = "Failed to parse storage configuration"
	_STORAGE_CA                  = "Failed to parse storage peers CA certificate"
	_STORAGE_CERT                = "Failed to parse storage service key and certificate"
	_STORAGE_ADDR                = "Invalid TCP address of storage service clients"
	_STORAGE_ADDR_PEER           = "Invalid TCP address of storage service peers"
	_STORAGE_ETCD_PARSE          = "Failed to parse storage peer certificate"
	_STORAGE_ETCD_CA_VERIFY      = "Failed to verify storage peer certificate against storage peer CA certificate"
	_STORAGE_ETCD_CA_VERIFY_EXT  = "Verification of peer certificate is only possible is certificate has proper x509 extension"
	_STORAGE_ETCD_CA_WRITE       = "Unable to write storage peer CA certificate to etcd directory"
	_STORAGE_ETCD_START          = "Start etcd binary"
	_STORAGE_ETCD_START_FAIL     = "Failed to start etcd binary"
	_STORAGE_ETCD_WAIT           = "Wait until systemd brings up etcd process up"
	_STORAGE_ETCD_STOP_FAIL      = "Failed to stop etcd binary gracefully"
	_STORAGE_ETCD_UNIX           = "Failed to connect to unix socket"
	_STORAGE_ETCD_UNIX_READ      = "Failed to read from unix socket"
	_STORAGE_ETCD_UNIX_READY     = "Expected to receive 'READY=1' on unix socket"
	_STORAGE_ETCD_STOP           = "Got stop signal from etcd"
	_STORAGE_OS_INTERRUPT        = "Got SIGINT signal from OS"
	_STORAGE_PROTOCOL            = "IVXV storage protocol is only allowed to be 'etcd'"
	_STORAGE_CTRL_CFG            = "Failed to parse controller configuration for storage service"
	_STORAGE_CTRL                = "Failed to create controller for storage service"
	_STORAGE_CTRL_SERVE          = "Failed to control a storage service"
)
