package main

const (
	_MID_EXPIRED_AUTH_SESSION = "Request timeout expired for this voter between RPC.Authenticate and RPC.AuthenticateStatus"
	_MID_AUTHREQ              = "RPC.AuthenticateReq"
	_MID_EXPIRED              = "Current time >= 'electionstoptime' from election configuration file"
	_MID_SESSION_ID           = "Malformed SessionID"
	_MID_SESSION_ID_EXPIRED   = "SessionID has been expired"
	_MID_AUTH_RESP            = "Mobile-ID provider responded with error"
	_MID_NO_RESP              = "Cannot reach Mobile-ID provider"
	_MID_DATA_TOKEN_CREATE    = "Failed to create data token cookie (AES cipher)"
	_MID_SAME_AUTH_SESSION    = "Mobile-ID provider has been issued duplicate authentication session code"
	_MID_AUTHRESP             = "RPC.AuthenticateResp"
	_MID_AUTHSTATUSREQ        = "RPC.AuthenticateStatusReq"
	_MID_UNKNOWN_AUTH_SESSION = "Voter send non-existing Mobile-ID authentication session code"
	_MID_SIG_RESP             = "Mobile-ID provider returned back voter's signature"
	_MID_NO_CERT_RESP         = "Mobile-ID provider didn't return back voter's certificate"
	_MID_CERT_RESP            = "Mobile-ID provider returned back voter's certificate"
	_MID_VERIFY_SIG           = "Failed to verify voter's signature"
	_MID_VOTER_ID             = "Cannot extract voter's personal code from certificate's 'Subject' field"
	_MID_AUTH_TOKEN_CREATE    = "Failed to create IVXV authentication token cookie (AES cipher)"
	_MID_AUTHSTATUSRESP       = "RPC.AuthenticateStatusResp"
	_MID_GETCERTREQ           = "RPC.GetCertificateReq"
	_MID_VOTER_NO_AUTH        = "Voter has not been authenticated"
	_MID_VOTER_NO_PHONENR     = "Authenticated voter should have a phone nr. parsed from IVXV authentication token cookie"
	_MID_CERT                 = "Mobile-ID signing certificate of a voter"
	_MID_GETCERTRESP          = "RPC.GetCertificateResp"
	_MID_SIGNREQ              = "RPC.SignReq"
	_MID_SIGNRESP             = "RPC.SignResp"
	_MID_SIGNSTATUSREQ        = "RPC.SignStatusReq"
	_MID_SIGNSTATUSRESP       = "RPC.SignStatusResp"
	_MID_START                = "Failed to transform service start time from election configuration file to RFC3339 format"
	_MID_AUTH_STOP            = "Failed to transform authentication stop time from election configuration file to RFC3339 format"
	_MID_STOP                 = "Failed to transform service stop time from election configuration file to RFC3339 format"
	_MID_CLIENT_CONF          = "Failed to configure Mobile-ID API client"
	_MID_TICKET_AUTH          = "Mobile-ID service should be configured for ticket based authentication"
	_MID_TICKET               = "Failed to create a Mobile-ID ticket (AES cipher) that is used for cookie signing"
	_MID_AUTH                 = "Failed to parse authentication configuration for mid service"
	_MID_SERVER               = "Failed to parse server configuration for mid service"
	_MID_SERVER_SERVE         = "Failed to serve mid service to clients"
)
